### ISSUE TITLE
Move jupyter notebooks to the mozilla-reports repository

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/telemetry-onboarding#9]
The "Telemetry Hello World" notebook is already there (and more up-to-date):
https://github.com/mozilla/mozilla-reports/tree/master/tutorials

**Comment by mreid-moz** [comment]
cc @harterrt

**Comment by harterrt** [comment]
I'm afraid this issue will get lost, does it make sense to [file against the documentation component](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody%40mozilla.org&bug_file_loc=http%3A%2F%2F&bug_ignored=0&bug_severity=normal&bug_status=NEW&cf_fx_iteration=---&cf_fx_points=---&component=Documentation%20and%20Knowledge%20Repo%20%28RTMO%29&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&defined_groups=1&flag_type-4=X&flag_type-607=X&flag_type-800=X&flag_type-803=X&flag_type-916=X&form_name=enter_bug&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Linux&priority=P3&product=Data%20Platform%20and%20Tools&rep_platform=x86_64&target_milestone=---&version=unspecified) instead?

**Comment by mreid-moz** [comment]
Yes, [good idea](https://bugzilla.mozilla.org/show_bug.cgi?id=1372571).
